- source/DruidXBasicAuthExtension/src/main/java/com/amazon/solutions/druid/xbasicauth/XBasicHTTPAuthenticator.java
- source/DruidXBasicAuthExtension/src/main/java/com/amazon/solutions/druid/xbasicauth/XBasicHTTPAuthorizer.java
Updates JsonTypeName for xbasic auth
> [POT-1099] Update xbasic auth type 

- source/DruidXBasicAuthExtension/src/main/java/com/amazon/solutions/druid/xbasic/XBasicAuthenticator.java
- source/DruidXBasicAuthExtension/src/main/java/com/amazon/solutions/druid/xbasic/XBasicAuthorizer.java
- source/DruidXBasicAuthExtension/src/main/java/com/amazon/solutions/druid/xbasic/XBasicDruidModule.java
- source/DruidXBasicAuthExtension/src/main/java/com/amazon/solutions/druid/xbasic/XBasicFilter.java
- source/DruidXBasicAuthExtension/src/main/resources/META-INF.services/org.apache.druid.initialization.DruidModule
- source/DruidXBasicAuthExtension/src/test/java/com/amazon/solutions/druid/xbasic/XBasicAuthenticatorTest.java
- source/DruidXBasicAuthExtension/src/test/java/com/amazon/solutions/druid/xbasic/XBasicAuthorizerTest.java
- source/DruidXBasicAuthExtension/src/test/java/com/amazon/solutions/druid/xbasic/XBasicFilterTest.java
- source/lib/uploads/config/_common/common.runtime.properties
- Registers xbasic extension as a module.
> [Pot-1099] Register xbasic module

- source/build-dependencies.sh
Fixes xbasic auth build command
> [POT-1099] Fix Build command

- source/build-dependencies.sh
> [POT-1099] Fix build 

- source/build-dependencies.sh
> add ll command

- source/build-dependencies.sh
> cd into correct folder

- source/DruidXBasicExtension/pom.xml
- source/DruidXBasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicAuthenticator.java
- source/DruidXBasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicAuthorizer.java
- source/DruidXBasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicConfig.java
- source/DruidXBasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicDruidModule.java
- source/DruidXBasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicFilter.java
- source/DruidXBasicExtension/src/main/resources/META-INF.services/org.apache.druid.initialization.DruidModule
- source/DruidXBasicExtension/src/test/java/com/amazon/solutions/druid/xbasic/XBasicAuthenticatorTest.java
- source/DruidXBasicExtension/src/test/java/com/amazon/solutions/druid/xbasic/XBasicAuthorizerTest.java
- source/bin/druid-infra.ts
> Pot 1099 basic auth 12

- source/DruidXBasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicDruidModule.java
> register named type

- source/build-dependencies.sh
> Fix xbasic directory name on build

- source/DruidXbasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicAuthenticator.java
- source/DruidXbasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicAuthorizer.java
- source/DruidXbasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicConfig.java
- source/DruidXbasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicDruidModule.java
> add config

- deployment/build-s3-dist.sh
- source/DruidXbasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicDruidModule.java
- source/DruidXbasicExtension/src/main/java/com/amazon/solutions/druid/xbasic/XbasicFilter.java
> Add logger when auth header is replaced

- source/lib/uploads/config/_common/common.runtime.properties
> Revert common runtime property changes

- source/build-dependencies.sh
> remove xbasic extension from build

- source/DruidOidcExtension/pom.xml
Bumps package version to fix vulns
> nimbus-jose-jwt 7.9 → 9.37.2

- source/DruidOidcExtension/pom.xml
> fix-nimbus-jose-jwt

- source/lib/constructs/baseInfrastructure.ts
> Force s3 upload

- source/DruidOidcExtension/pom.xml
> Remove nimbus-jose-jwt dependency

- source/DruidOidcExtension/src/main/java/com/amazon/solutions/druid/oidc/OidcFilter.java
> update pac4j changes

- source/DruidOidcExtension/src/test/java/com/amazon/solutions/druid/oidc/OidcFilterTest.java
> Upgrade Pac4j 

- source/DruidOidcExtension/pom.xml
> Bump Nimbus-jwt version

- source/DruidOidcExtension/pom.xml
> Bump pac4j

- source/DruidOidcExtension/pom.xml
- source/DruidOidcExtension/src/main/java/com/amazon/solutions/druid/oidc/OidcFilter.java
- source/DruidOidcExtension/src/test/java/com/amazon/solutions/druid/oidc/OidcFilterTest.java
update deprecated several dependencies and moved them to new packages. This PR adds missing dependencies
> fix broken pac4j dependencies
